apiVersion: v1
kind: ConfigMap
metadata:
  name: default-local
binaryData:
  default-local.tar.gz: H4sIAAAAAAAAA+3RQW+CMBgGYM7+iqanzWSUCoVohvEH7LYddm2gTpNSSFuHJP74qWimS8wuGrPsfS7NB9/XFt5SzeVKe6brQmoW3ES0lQmxW3km+Ol6FHDB4yzOeBQnQcTjUZQGRNzmOudWzktLSGBXxih7ue+3939UeZb/slTGL30Xrp2+3hm7gNMkuZh/nKQ/8hciGwUkut4VLvvn+T9vk54432nlFkp58qmsW9YmpzyMKFlX2rjJtiWnC++bCWNt24ZtHNb2g/HxeMzeX1/Ym5XGzWtb0emAkP2OXlWNll6RSvpikVNTl+rhcTMb7lsOTUXddH15eCCbRndPx1lHnNKq8DmdDTf9BpQdxtnpfF8dx6aDvv7+qOng3n8ZAAAAAAAAAAAAAAAAAAAAAOA2vgCFq/2UACgAAA==
