apiVersion: v1
kind: ConfigMap
metadata:
  name: default-local
binaryData:
  default-local.tar.gz: H4sIAAAAAAAAA+3TQW+CMBQHcM5+iqanzWSUikg0w/gBdtsOuzZQp0kppK1DEj/8UDTTZbpk0W1m/9+B5sF7pfDyMjkVC+WYKlKhmHcRQSOOovXK44jvrzsej3gYh03WIPYCHvZ6kUeiyxzn0MI6YQjxzEJraY7nffX8SmUH/Z9nUru5q3v+0qqzvWPd4EG/f7T/YX/wof/NNfRIcLYTnPDP+3/fNHpkXa2knUnpyKs0dl7ohHI/oGSZK21HTUpCZ86VI8aqqvKr0C/MC+PD4ZA9Pz6wJyO0nRYmp+MOIZsdncxLJZwkuXDpLKG6yOTN7WrS3aRsk9KirNtwe0OUparvdrWWWKlk6hI66a7aDSjblrP9+jbalY07bfz+UePOb//lv+vz+T/r+H9r/jnH/P8EzD8AAAAAAAAAAAAAAAAAAMD1ewPZqYf5ACgAAA==
