apiVersion: v1
kind: ConfigMap
metadata:
  name: default-local
binaryData:
  default-local.tar.gz: H4sIAAAAAAAAA+3RQW+CMBgGYM7+iqanzWSUDgvRDOMP2G077NpAnSalkLYOSfzxQ9FMl5BdNMuy97k0X/m+UngLtZQb7ZmucqlZcBNRJxViv/JU8PP1JOCCx2mcpCLu9nn8yEVAxG2uc2njvLSEBHZjjLLDfT89/6OKi/zXhTJ+7dtw6/T13rEPOJlMBvOPJ8m3/EUS8YBE17vCsH+e/1OX9Mz5Viu3UsqTD2XdujIZ5WFEybbUxs26loyuvK9njDVNEzZxWNl3xqfTKXt7eWavVhq3rGxJ5yNCDid6VdZaekVK6fNVRk1VqLv73WJ8aDk25VXd9uVxQ9a1bh9Os444pVXuM7oY7/oDKDuOs/P5vjqNzUd9/fVR89Fv/2UAAAAAAAAAAAAAAAAAAAAAgNv4BL1+3QAAKAAA
