apiVersion: v1
kind: ConfigMap
metadata:
  name: default-local
binaryData:
  default-local.tar.gz: H4sIAAAAAAAAA+3RQW+CMBgGYM7+iqanzWSUCoVohvEH7LYddm2gTpNSSFuHJP74qWimS8wuGrPsfS7NB9/XFt5SzeVKe6brQmoW3ES0lQmxW3km+Ol6FHDB4yzOOB+lQcTjEY8CIm5znXMr56UlJLArY5S93Pfb+z+qPMt/WSrjl74L105f74xdwGmSXMw/TtIf+QuRJQGJrneFy/55/s/bpCfOd1q5hVKefCrrlrXJKQ8jStaVNm6ybcnpwvtmwljbtmEbh7X9YHw8HrP31xf2ZqVx89pWdDogZL+jV1WjpVekkr5Y5NTUpXp43MyG+5ZDU1E3XV8eHsim0d3TcdYRp7QqfE5nw02/AWWHcXY631fHsemgr78/ajq4918GAAAAAAAAAAAAAAAAAAAAALiNL/6n9CcAKAAA
