apiVersion: v1
kind: ConfigMap
metadata:
  name: default-local
binaryData:
  default-local.tar.gz: H4sIAAAAAAAAA+3RQW+CMBgGYM7+iqanzWSUipVohvEH7LYddm2gTpNSSFuGJP74qWimS8wuErPsfS7NB9/XFt5cLWWtPdNlJjULehHtJELsV54Ifr6eBFzwOImTKJ6MgojHI84DIvq5zqXaeWkJCWxtjLLX+357/0flF/mvc2X82rfhxunbnbEPeDIeX80/Hk9+5C9EIgIS3e4K1/3z/J93Sc+cb7VyK6U8+VTWrUuTUh5GlGwKbdxs15LSlffVjLGmacImDkv7wfh0OmXvry/szUrjlqUt6HxAyGFHr4pKS69IIX22Sqkpc/XwuF0MDy3Hpqys2q48PpBVpdun06wjTmmV+ZQuhttuA8qO4+x8vqtOY/NBV39/1Hxw778MAAAAAAAAAAAAAAAAAAAAANCPL84CnUIAKAAA
